---
abstract: 'A module for reading .ini-style configuration files.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: 0
  List::Util: 0
  Scalar::Util: 0
  Test::More: 0
  base: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
keywords:
  - ini
  - files
  - config
  - configuration
  - 'ini files'
  - windows
  - tie
  - pure-perl
  - tested
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-IniFiles
provides:
  Config::IniFiles:
    file: lib/Config/IniFiles.pm
    version: 2.79
requires:
  Carp: 0
  Fcntl: 0
  File::Basename: 0
  File::Temp: 0
  List::MoreUtils: 0.33
  Symbol: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://sourceforge.net/projects/config-inifiles/
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/shlomif/perl-config-inifiles
version: 2.79
