---
name: Config-IniFiles
version: 2.45
author: []
abstract: A module for reading .ini-style configuration files.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Symbol: 0
  strict: 0
  warnings: 0
build_requires:
  File::Spec: 0
  Scalar::Util: 0
provides:
  Config::IniFiles:
    file: lib/Config/IniFiles.pm
    version: 2.45
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
